### ISSUE TITLE
Not implemented instruction list

### ISSUE THREAD

**Issue by iksw** [vproc/vicuna#56]
Hi,

Where can I find which instructions are not implemented?

**Comment by michael-platzer** [comment]
Hi @iksw

Vicuna implements the `Zve32x` extension defined in the [RISC-V V specification](https://github.com/riscv/riscv-v-spec) (see Sect. 18.2), with the exception of the division and remainder instructions (due to the current lack of a hardware divider).

All other instructions that are part of this extension are implemented. Did you encounter an issue with some instruction?

**Comment by michael-platzer** [comment]
Closing this as it seems the question has been answered. Please feel free to reopen or opening another issue if you encounter problems with some instruction.
